In [2]:
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np

In [7]:
embeddings_layer = layers.Embedding(1000,5)

data = tf.constant([1,2,3,4])

result = embeddings_layer(data)

print(result)

tf.Tensor(
[[ 0.01483924  0.04020521 -0.02992852  0.04940747  0.02413363]
 [ 0.04301443 -0.00700309  0.03897263 -0.03940688  0.04141018]
 [-0.00778183  0.03101427  0.04379281  0.02964788  0.0460611 ]
 [ 0.02158561  0.02564045  0.04255289  0.02504556 -0.04759538]], shape=(4, 5), dtype=float32)
