In [2]:
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np

In [7]:
embeddings_layer = layers.Embedding(1000,5)

data = tf.constant([1,2,3,4])

result = embeddings_layer(data)

print(result)

tf.Tensor(
[[ 0.01483924  0.04020521 -0.02992852  0.04940747  0.02413363]
 [ 0.04301443 -0.00700309  0.03897263 -0.03940688  0.04141018]
 [-0.00778183  0.03101427  0.04379281  0.02964788  0.0460611 ]
 [ 0.02158561  0.02564045  0.04255289  0.02504556 -0.04759538]], shape=(4, 5), dtype=float32)


In [11]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

documents = [
    "The cat sat on the mat.",
    "The dog played in the garden.",
    "The cat and the dog are friends."
]

# Create CountVectorizer with max_features and stop_words
vectorizer = CountVectorizer(max_features=20)
# Fit and transform the documents (X is a sparse matrix)
X = vectorizer.fit_transform(documents)
# Get the feature names (words)
feature_names = vectorizer.get_feature_names_out()
# Convert the matrix to an array and create a DataFrame for better visualization
df = pd.DataFrame(X.toarray(), columns=feature_names)
# Display the DataFrame
print(df)
print(len(df.columns))

   and  are  cat  dog  friends  garden  in  mat  on  played  sat  the
0    0    0    1    0        0       0   0    1   1       0    1    2
1    0    0    0    1        0       1   1    0   0       1    0    2
2    1    1    1    1        1       0   0    0   0       0    0    2
12
